name: StressTests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 2 * * *'

jobs:
  endurance:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: go mod download

      - name: Run stress Tests
        run: |
          go test -v -count=1 -timeout=45m -run Test5Nodes1kTearDown ./... | tee testlogs.log

      - name: Upload Logs
        uses: actions/upload-artifact@v3
        with:
          name: endurance-logs
          path: testlogs.log
