name: Endurance Tests

on:
  push:
    branches: [ "stress_test" ]

jobs:
  endurance:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Initialize & update submodules
        run: git submodule update --init --recursive

      - name: Prepare third_party directory
        run: |
          sudo mkdir -p third_party
          sudo chown $USER third_party

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install Go dependencies
        run: go mod download

      - name: Build nwaku dependencies
        run: make -C waku

      - name: Run Stress Test
        run: |
          go test -v ./waku/stress_test.go -count=1 -timeout=360m | tee testlogs.log

      - name: Upload Test Logs
        uses: actions/upload-artifact@v4
        with:
          name: endurance-logs
          path: testlogs.log
